function searchRecords() {
    const searchInput = document.getElementById("searchInput");
    const resultsDiv = document.getElementById("results");
    resultsDiv.innerHTML = ""; // Limpiar resultados anteriores

    // Obtener IDs ingresados y dividirlos por comas
    const ids = searchInput.value.split(",");

    for (const id of ids) {
        // Simular la búsqueda de registros por ID (puedes reemplazar esto con tus propios datos)
        const record = findRecordById(id.trim()); // Aquí deberías implementar tu lógica de búsqueda

        if (record) {
            // Si se encuentra el registro, mostrarlo
            const resultItem = document.createElement("div");
            resultItem.innerText = `${id.trim()}: ${record}`;
            resultsDiv.appendChild(resultItem);
        } else {
            // Si no se encuentra el registro, mostrar un mensaje de error
            const errorItem = document.createElement("div");
            errorItem.innerText = `ID: ${id.trim()} no encontrado`;
            errorItem.classList.add("error");
            resultsDiv.appendChild(errorItem);
        }
    }
}

// Función de ejemplo para buscar registros por ID (debes implementar la tuya)
function findRecordById(id) {
    // Aquí puedes agregar tu lógica de búsqueda de registros
    const records = {
        "1": "Your sexy body has me drooling - Tu cuerpo sexy me tiene babeando",
        "2": "I share with you unselfishly - Comparto contigo desinteresadament",
        "3": "I acknowledge my mistakes with you - Reconozco mis errores contigo",
        "4": "Life is a gift, and you are the most beautiful thing in it. - La vida es un regalo, y tú eres lo más lindo en él",
        "5": "I have fantasies about what I want to do with you - Tengo fantasías acerca de lo que quiero hacer contigo",
        "6": "I know in my heart that we'll be together again - Yo sé en mi corazón que volveremos a estar juntos de nuevo",
        "7": "I thought I would surprise you with a quote - He pensado en sorprenderte con una cita",
        "8": "I can't understand why I still feel a connection with you. - No puedo entender porque aún me siento en conexión contigo",
        "9": "I ran away from you because I felt overwhelmed - Hui de ti porque me sentí abrumada",
        "10": "I want to commit to you when I feel ready for you. - Me quiero comprometer contigo cuando me sienta lista/o para ti",
        "11": "I need your time and commitment - Necesito tu tiempo y compromiso",
        "12": "You need to let go so I can grow up - Necesitas soltarme para que yo pueda crecer",
        "13": "Give me a couple of days please - Dame un par de días por favor",
        "14": "I have acted very childish and I don't know how to approach it now. - He actuado muy infantil y no sé cómo acercarme ahora",
        "15": "I am letting go of everything that no longer serves me - Estoy soltando todo lo que ya no me sirve",
        "16": "I keep hoping this will work out between us - Sigo esperando que esto funcione entre nosotros",
        "17": "I don't need you to fix me, I need you to love me, while I try to fix myself. - No necesito que me arregles, necesito que me ames, mientras intento arreglarme a mí mismo/a",
        "18": "I tried to run away from this connection but my soul longs for you - Intenté huir de esta conexión pero mi alma te anhela",
        "19": "I'm thinking about how to approach you - Estoy pensando en cómo acercarme a ti",
        "20": "Finally I'm going to put you first - Finalmente voy a ponerte primero",
        "21": "My biggest regret is having let you go - Mi más grande arrepentimiento es haberte dejado ir",
        "22": "I am sorry for having betrayed your trust - Lo siento por haber traicionado tu confianza",
        "23": "I find you incredibly attractive - Te encuentro increíblemente atractivo/a",
        "24": "Children (family, pets, or friends) are important to this couple. - Los niños (familia, mascotas o amigos) son importantes para esta pareja",
        "25": "I get distracted thinking about you - Me distraigo pensando en ti",
        "26": "Is it too late for a second chance? - ¿Es demasiado tarde para una segunda oportunidad?",
        "27": "I need more time to figure out what I want - Necesito más tiempo para averiguar lo que quiero",
        "28": "You caught me and I don't know how to act - Me atrapaste y no sé cómo actuar.",
        "29": "I should never let you go - Nunca debería dejarte ir",
        "30": "I'm dreaming of you - Estoy soñando contigo.",
        "31": "Our story is not over yet - Nuestra historia aún no ha terminado.",
        "32": "I'm not ready for such a great love - No estoy listo para un amor tan grande.",
        "33": "Your family and friends will not like me - No le gustaré a tu familia y amigos.",
        "34": "Your family and friends do not like me - No le agrado a tu familia y amigos.",
        "35": "I don't want to face the truth right now - No quiero enfrentarme a la verdad ahora mismo.",
        "36": "You are the only person who really understands me - Eres la única persona que realmente me entiende.",
        "37": "My pride and ego got hurt, so I wanted to reverse, I wanted you to get hurt too. - Mi orgullo y mi ego se lastimaron, así que quise revertir, quise que tú también te lastimaras.",
        "38": "You inspire me to be a better person - Me inspiras a ser mejor persona.",
        "39": "I am thinking of contacting you - Estoy pensando en ponerme en contacto contigo.",
        "40": "Separate time will bring us the clarity we seek - El tiempo separados nos traerá la claridad que buscamos.",
        "41": "I will come back to you... when I'm ready - Volveré a ti... cuando esté listo.",
        "42": "My life is not as good as it seems. - Mi vida no es tan buena como parece.",
        "43": "I feel excited when I see you - Me siento excitado cuando te veo.",
        "44": "I'm starting to see what this connection is really about - Estoy empezando a ver lo que esta conexión es realmente.",
        "45": "The grass was no longer green on the other side - La hierba no era más verde al otro lado.",
        "46": "This makes me feel insecure - Esto me hace sentir insegur@.",
        "47": "I have sexual fantasies about you - Tengo fantasías sexuales contigo.",
        "48": "I'm struggling to open up to you - Estoy luchando por abrirme a ti.",
        "49": "I still don't understand what happened between us...How did it all fall apart? - Todavía no entiendo lo que pasó entre nosotros... ¿Cómo se vino todo abajo?",
        "50": "The war of the social networks - La guerra de las redes sociales…",
        "51": "I meant what I said - Quise decir lo que dije.",
        "52": "I ignore you because it's easier than telling you the truth. - Te ignoro porque es más fácil que decirte la verdad.",
        "53": "Now I am finally facing the consequences of my actions. - Ahora por fin me enfrento a las consecuencias de mis acciones.",
        "54": "I can't seem to forget you - Parece que no puedo olvidarte.",
        "55": "No matter how much time passes, you are still important to me. - No importa cuanto tiempo pase, aún sigues siendo importante para mi.",
        "56": "I feel that you and I have nothing in common. - Siento que tú y yo no tenemos nada en común.",
        "57": "I'm not interested in sharing time with you right now, but I don't know how to tell you. - No me interesa compartir tiempo contigo ahora, pero no sé cómo decírtelo.",
        "58": "Everything is magical when we are together - Todo es mágico cuando estamos juntos.",
        "59": "I have thoughts of love with you - Tengo pensamientos de amor contigo.",
        "60": "I find it hard to assume my feelings for you - Me cuesta asumir mis sentimientos por ti.",
        "61": "I don't want to have anything to do with you right now - No quiero tener nada contigo en este momento.",
        "62": "Family or friends may not agree with this connection. - Familiares o amigos pueden no estar de acuerdo con esta conexión.",
        "63": "I'm afraid of your rejection - Tengo miedo de tu rechazo.",
        "64": "I see you in a whole new light. - Te veo bajo una luz totalmente nueva.",
        "65": "You changed me forever, you're tattooed in my heart - Me cambiaste para siempre, estás tatuado en mi corazón.",
        "66": "Other people do not want us to be together - Otras personas no quieren que estemos juntos.",
        "67": "I regret having lied to you - Me arrepiento de haber te mentido.",
        "68": "I just can't accept the truth about us - Simplemente no puedo aceptar la verdad sobre nosotros.",
        "69": "I don't see your actions, they are just promises - No veo tus acciones, son solo promesas.",
        "70": "I feel lost without you in my life - Me siento perdido sin ti en mi vida.",
        "71": "No matter who I'm with, my channels always lead me to you. - No importa con quién esté, mis canales siempre me llevan a ti.",
        "72": "I can't get past you… - No puedo pasar de ti…",
        "73": "I can't go on with you - No puedo seguir adelante contigo.",
        "74": "What you are feeling, I feel it too. - Lo que estás sintiendo, yo lo siento también.",
        "75": "I want everything from you. - Deseo todo de ti.",
        "76": "Please do not make assumptions about me without evidence. - Por favor, no hagas suposiciones sobre mí sin pruebas.",
        "77": "I regret it, I thought I could forget you; and I cannot. - Me arrepiento, pensé que podría olvidarte; y no puedo.",
        "78": "I don't think it's right for us to be together now. - No me parece bien que estemos juntos ahora.",
        "79": "I see you in my dreams. - Te veo en mis sueños.",
        "80": "I am learning valuable soul lessons right now. - Estoy aprendiendo valiosas lecciones del alma ahora mismo.",
        "81": "I want to talk to you again. - Quiero volver a hablar contigo.",
        "82": "My 'I love yous' are forced - Mis 'Te amo' son forzados.",
        "83": "My pride lasts longer than before - Mí orgullo dura más tiempo que antes.",
        "84": "I ignore you and take a long time to answer your messages in a conscientious way. - Te ignoro y tardo en contestar tus mensajes de manera consciente.",
        "85": "I always make excuses with you not to see you and tell you the truth. - Siempre pongo excusas contigo para no verte y decirte la verdad.",
        "86": "I'm sorry, forgive me - Lo siento, perdóname.",
        "87": "I believe in you, in your magic and what you make me feel. - Creo en ti, en tu magia y lo que me haces sentir.",
        "88": "The healthiest thing to do is not to insist where you feel there is no desire. - Lo más sano es no insistir en donde notas que no hay ganas.",
        "89": "Light always looks better in the dark - La luz siempre se ve mejor en la oscuridad.",
        "90": "I will treat you the same way you treat me - Te trataré de la misma forma en que me trates.",
        "91": "I decided to focus on myself - Decidí centrarme en mí.",
        "92": "You may not notice it, but I'm trying really hard - Tal vez no se note, pero me estoy esforzando mucho.",
        "93": "Life becomes easier when I have you near - La vida es más fácil cuando te tengo cerca.",
        "94": "Don't feel comfortable because it's been a long time. - No te sientas cómodo porque haya pasado mucho tiempo.",
        "95": "I pay attention to actions, but not to words. - Presto atención a las acciones, pero no a las palabras.",
        "96": "I heard what you said, but I see how you act. - Escuché lo que dijiste, pero veo cómo actúas.",
        "97": "I put my energy and attention on what really makes me happy. - Pongo mi energía y atención en lo que realmente me hace feliz.",
        "98": "I'm fine, but if I think too much I miss you - Estoy bien, pero si pienso mucho te extraño.",
        "99": "Letting go is not easy. Especially when it's someone who is important to me. - Soltar no es fácil. Y mucho menos cuando se trata de alguien que es importante para mí.",
        "100": "Saying goodbye out of obligation hurts - Despedirse por obligación duele.",
        "101": "If I don't look for you, it's because I don't need you - Si no te busco, es porque no me haces falta.",
        "102": "I don't know what to do to rest and not think about you - No sé qué hacer para descansar y no pensar en ti.",
        "103": "I feel you are too worthwhile - Siento que vales demasiado la pena.",
        "104": "I want you to be my team, not my torment. - Quiero que seas mi equipo, no mi tormento.",
        "105": "I like the way I feel with you - Me gusta como me siento contigo.",
        "106": "If you saw the size of my feelings for you, you would understand the magnitude of my battle. - Si vieras el tamaño de mis sentimientos por ti, entenderías la magnitud de mi batalla.",
        "107": "If you saw yourself as I see you through my eyes, you would understand me - Si te vieras como yo te veo a ti a través de mis ojos, me entenderías.",
        "108": "I need time to assimilate and process everything I am feeling for you. - Necesito tiempo para asimilar y procesar todo lo que estoy sintiendo por ti.",
        "109": "I change my perspective and take opportunities to grow and learn. - Cambio de perspectiva y tomo las oportunidades para crecer y aprender.",
        "110": "Even if the going gets tough, I want to be there with you. - Aunque las cosas se pongan difíciles, quiero estar ahí contigo.",
        "111": "I feel responsibility for things that are beyond my control. - Siento responsabilidad por cosas que están fuera de mi control.",
        "112": "I focus on the negative aspects of a situation - Me centro en los aspectos negativos de una situación.",
        "113": "Emotionally exhausted - Emocionalmente agotado.",
        "114": "I'm curious to know everything you do - Tengo curiosidad por saber todo lo que haces.",
        "115": "You are my safe place in the world, with you everything stops being gray. - Eres mí lugar seguro en el mundo, contigo todo deja se ser gris.",
        "116": "I'm afraid to be vulnerable with you - Tengo miedo de mostrarme vulnerable contigo.",
        "117": "I accept our differences - Acepto nuestras diferencias.",
        "118": "I feel a great excitement when you are near me - Siento una gran excitación cuando te tengo cerca.",
        "119": "I feel a deep emotional connection with you and I can't ignore it. - Siento una conexión emocional profunda contigo y no puedo ignorarlo.",
        "120": "Not every day is a good day, but with you it gets better. - No todos los días son buenos, pero contigo se hacen mejores.",
        "121": "I'm sorry if I sometimes behave strangely or rudely, my head is a mess.. - Perdón si a veces me comporto raro o cortante, mi cabeza es un lío.",
        "122": "Letting you go hurts me - Dejarte ir me duele.",
        "123": "There's something about you that I find addictive… - Hay algo de ti que me resulta adictivo…",
        "124": "I don't like what I see in the mirror - No me gusta lo que veo en el espejo.",
        "125": "I know I have to work on myself and my thoughts. - Sé que tengo que trabajar en mí y en mis pensamientos.",
        "126": "I blame you for everything - Te culpo por todo.",
        "127": "I miss you, more than you think I do - Te echo de menos, más de lo que crees.",
        "128": "Twin flame - Llama gemela.",
        "129": "You changed me forever, you're tattooed in my heart - Me cambiaste para siempre, estás tatuada en mi corazón.",
        "130": "Secret love - Amor secreto.",
        "131": "I want to know everything about you - Quiero conocer todo de ti.",
        "132": "I have to mind my own business - Tengo que ocuparme de mis asuntos.",
        "133": "Alone in the world - Solo en el mundo.",
        "134": "Hiding the real me - Ocultando mi verdadero yo.",
        "135": "I'm focused on me - Estoy concentrado en mí.",
        "136": "Everything is chaos and confusion in me now - Todo es caos y confusión en mí ahora.",
        "137": "I cannot recognize myself. But I'm still me. - No puedo reconocerme. Pero sigo siendo yo.",
        "138": "There is nothing else that can replace my focus - No hay nada más que pueda reemplazar mi enfoque.",
        "139": "Quiet among thorns - Tranquilo entre espinas.",
        "140": "It is better not to feel, rather than feeling pain - Es mejor no sentir, que sentir dolor.",
        "141": "Loosening ties - Soltando ataduras.",
        "142": "You give me clarity, the light that I needed - Me das claridad, la luz que necesitaba.",
        "143": "I dive in and out of relationships - Entro y salgo de relaciones.",
        "144": "Your memory lives in me - Tu recuerdo vive en mí.",
        "145": "Your voice echoes in my mind - Tu voz resuena en mi mente.",
        "146": "Something keeps me pulling back to you - Algo me hace volver a ti.",
        "147": "I don´t know how long, it will take for me to heal - No sé cuánto tiempo tardaré en curarme.",
        "148": "There´s so much unresolved stuff between us… - Hay tantas cosas sin resolver entre nosotros…",
        "149": "I miss our conversations and the sound of your voice - Echo de menos nuestras conversaciones y el sonido de tu voz.",
        "150": "I´m looking for advice in friends and family - Busco consejo en amigos y familia.",
        "151": "I´m paying for karma, i´m facing my demons - Estoy pagando por el karma, me estoy enfrentando a mis demonios.",
        "152": "My mind is saying No but my heart is saying YES - Mi mente dice No pero mi corazón dice SI.",
        "153": "I´m talking to someone new… - Estoy hablando con alguien nuevo…",
        "154": "I feel like i'm dying inside - Siento que me estoy muriendo por dentro.",
        "155": "There´s a big hole in my heart that i cannot fill on my own - Hay un gran agujero en mi corazón que no puedo llenar por mi cuenta.",
        "156": "I am seeing you in a whole new light - Te estoy viendo bajo una luz completamente nueva.",
        "157": "I feel overwhelmed, i'm drowning in my own thoughts - Me siento abrumado, me estoy ahogando en mis propios pensamientos.",
        "158": "I want a fresh start with you! - ¡Quiero un nuevo comienzo contigo!",
        "159": "You´re a goddess to me… - Eres una diosa para mí…",
        "160": "You consume my mind - Tu consumes mi mente.",
        "161": "I don't feel enough for you - No me siento suficiente para ti.",
        "162": "I want to go back to the past where I felt happy - Quiero volver al pasado donde me sentía feliz.",
        "163": "I relish the idea of releasing all the brakes. - Saboreo la idea de soltar todo el freno.",
        "164": "What i can´t have forever, i will have for a minute. - Lo que no puedo tener para siempre, lo tendré por un minuto.",
        "165": "No progress is no regress either - Sin progreso tampoco hay retroceso.",
        "166": "Downcast pride - Orgullo abatido.",
        "167": "I won´t cry for you - No lloraré por ti.",
        "168": "I close my eyes and I keep thinking of you - Cierro los ojos y me la paso pensando en ti.",
        "169": "I accept all the burden and responsibility - Acepto toda la carga y la responsabilidad.",
        "170": "You are magic - Eres mágico.",
        "171": "Everything is possible with you - Todo es posible contigo.",
        "172": "Your presence consumes me completely - Tu presencia me consume por completo.",
        "173": "Every encounter with you is a new chapter in our story... - Cada encuentro contigo es un capítulo nuevo de nuestra historia.",
        "174": "You awaken my desire - Despiertas mi deseo…",
        "175": "Your actions do not go unnoticed by me. - Tus acciones no pasan desapercibidas para mí.",
        "176": "Exchange of complicit glances - Intercambio de miradas cómplices.",
        "177": "I feel the chemistry between us - Siento la química entre nosotros.",
        "178": "Even though we are far away, I feel you close - Aunque estemos lejos, te siento cerca.",
        "179": "I need to rest and renew my energy - Necesito descansar y renovar mis energías.",
        "180": "You can be far from my eyes, but not from my thoughts - Puedes estar lejos de mis ojos, pero no de mis pensamientos.",
        "181": "The desire to see you again consumes me… - Me consumen las ganas de volver a verte…",
        "182": "Your spirit irritates my demons… - Tu espíritu irrita mis demonios…",
        "183": "Fear was our worst counselor - El miedo fué nuestro peor consejero.",
        "184": "I have everything except you - Lo tengo todo menos a ti.",
        "185": "If I have to wait for you, I will… - Si me toca esperarte lo haré...",
        "186": "I compare you with other people - Te comparo con otras personas.",
        "187": "You stand out from the crowd - Destacas entre la multitud.",
        "188": "You are a role model to me - Eres un modelo a seguir para mí.",
        "189": "I am proud of you - Estoy orgulloso de ti.",
        "190": "Something more than friends… - Algo más que amigos…",
        "191": "I am tormented by fears of the past - Me atormentan miedos del pasado.",
        "192": "I isolate myself socially as a defense mechanism. - Me aíslo socialmente como mecanismo de defensa.",
        "193": "Between wind and tide - Entre viento y marea.",
        "194": "Feeling things without you even touching me - Sintiendo cosas sin que siquiera me toques.",
        "195": "Daydreaming - Soñando despierto.",
        "196": "In the end this has been the best thing - Al final esto ha sido lo mejor.",
        "197": "You speak to me and move my world - Me hablas y mueves mi mundo.",
        "198": "I misjudged you - Te juzgué equivocadamente.",
        "199": "I was influenced by third parties - Fui influenciado por terceros.",
        "200": "My ego and pride are bigger than me - Mi ego y orgullo son más grandes que yo.",
        "201": "I have so many things to tell you - Tengo tantas cosas que contarte.",
        "202": "We need time to heal and grow on our own - Necesitamos tiempo para curarnos y crecer.",
        "203": "I wish I had fought harder for us - Ojalá hubiera luchado más por nosotros.",
        "204": "I hid who I really am from you - Te oculté quién soy en realidad.",
        "205": "I hope our paths cross again - Espero que nuestros caminos se vuelvan a cruzar.",
        "206": "I remember how we used to talk for hours about everything...miss you - Recuerdo cómo solíamos hablar durante horas sobre cualquier cosa... te echo de menos.",
        "207": "I am distracting myself to avoid thinking of you - Me estoy distrayendo para no pensar en ti.",
        "208": "I´m stuck until the lesson is learned - Estoy atascado hasta que se aprenda la lección.",
        "209": "I´m scared of this intense love - Tengo miedo de este amor intenso.",
        "210": "I am afraid you won't answer, that's why I don't dare to...communicate with you - Me temo que no quieres responderme, por eso no me atrevo a comunicarme contigo.",
        "211": "I'm talking to someone else… - Estoy hablando con alguien más…",
        "212": "I did not follow my heart - No seguí a mi corazón.",
        "213": "Please don´t walk away from me - Por favor, no te alejes de mí.",
        "214": "I remember you - Te recuerdo.",
        "215": "I am willing to change for you - Estoy dispuesto a cambiar por ti.",
        "216": "Even if we never meet again, you will always hold the key to my heart - Aunque no volvamos a vernos, siempre tendrás la llave de mi corazón.",
        "217": "I wish you would knock my door - Ojalá llamaras a mi puerta.",
        "218": "You´re the only one that truly gets me... - Eres el único que realmente me entiende...",
        "219": "I am sorry, for all the pain I caused to you... - Lo siento, por todo el dolor que te he causado...",
        "220": "Little by little, I come to terms with my feelings for you - Poco a poco, asumo mis sentimientos por ti…",
        "221": "I will insist until you forgive me... - Insistiré hasta que me perdones...",
        "222": "I´m not going to give you up - No voy a renunciar a ti…",
        "223": "I desire you - Te deseo…",
        "224": "A Back and forth between us - Un ir y venir entre nosotros…",
        "225": "I need to heal my own issues first... - Primero necesito curar mis propios problemas…",
        "226": "I know you have better options than me... - Sé que tienes mejores opciones que yo…",
        "227": "You´re always on my mind - Siempre estás en mi mente.",
        "228": "I´m hiding my true feelings... - Estoy ocultando mis verdaderos sentimientos…",
        "229": "The timing wasn't right for us... - No era el momento adecuado para nosotros…",
        "230": "You´re all I've ever wanted... - Eres todo lo que siempre he querido…",
        "231": "I would like to hear from you - Me gustaría saber de ti…",
        "232": "Not all that glitters is gold - No todo lo que brilla es oro…",
        "233": "I manipulate you to get what I want - Te manipulo para conseguir lo que quiero.",
        "234": "I am focused on my goals - Estoy centrado en mis objetivos.",
        "235": "I feel like I'm falling in love with you… - Siento que me estoy enamorando de tí…",
        
    };

    return records[id] || null;
}
